db = {'clientes': [{'cpf_cliente': '12345678901',
               'id_cliente': 1,
               'idade_cliente': 34,
               'nome_cliente': 'Mariana Lima Santos',
               'sexo_cliente': 'Feminino',
               'tipo_cliente': 'PF'},
              {'cpf_cliente': '01234567000188',
               'id_cliente': 2,
               'idade_cliente': 8,
               'nome_cliente': 'TecnoSoluções Ltda',
               'sexo_cliente': 'N/A',
               'tipo_cliente': 'PJ'},
              {'cpf_cliente': '98765432109',
               'id_cliente': 3,
               'idade_cliente': 52,
               'nome_cliente': 'Ricardo Almeida',
               'sexo_cliente': 'Masculino',
               'tipo_cliente': 'PF'},
              {'cpf_cliente': '11223344556',
               'id_cliente': 4,
               'idade_cliente': 25,
               'nome_cliente': 'Fernanda Costa',
               'sexo_cliente': 'Feminino',
               'tipo_cliente': 'PF'},
              {'cpf_cliente': '88776655000144',
               'id_cliente': 5,
               'idade_cliente': 15,
               'nome_cliente': 'ConstruForte Engenharia',
               'sexo_cliente': 'N/A',
               'tipo_cliente': 'PJ'},
              {'cpf_cliente': '66554433221',
               'id_cliente': 6,
               'idade_cliente': 41,
               'nome_cliente': 'Lucas Pereira',
               'sexo_cliente': 'Masculino',
               'tipo_cliente': 'PF'}],
 'config': {'taxa_rendimento_poupanca': 0.005},
 'contas': [{'ativa': True,
             'id_cliente': 1,
             'id_conta': 1,
             'saldo': 3450.6,
             'tipo_conta': 'Corrente'},
            {'ativa': True,
             'id_cliente': 1,
             'id_conta': 2,
             'saldo': 25800.0,
             'tipo_conta': 'Poupança'},
            {'ativa': True,
             'id_cliente': 2,
             'id_conta': 3,
             'saldo': 115234.98,
             'tipo_conta': 'Corrente'},
            {'ativa': True,
             'id_cliente': 3,
             'id_conta': 4,
             'saldo': 189500.55,
             'tipo_conta': 'Poupança'},
            {'ativa': True,
             'id_cliente': 4,
             'id_conta': 5,
             'saldo': 890.1,
             'tipo_conta': 'Corrente'},
            {'ativa': True,
             'id_cliente': 5,
             'id_conta': 6,
             'saldo': 0.0,
             'tipo_conta': 'Corrente'},
            {'ativa': False,
             'id_cliente': 6,
             'id_conta': 7,
             'saldo': -50.25,
             'tipo_conta': 'Corrente'}],
 'proximo_id_cliente': 7,
 'proximo_id_conta': 8,
 'proximo_id_transacao': 12,
 'transacoes': [{'data': '2025-09-10 10:22:05',
                 'id_conta': 1,
                 'id_transacao': 1,
                 'tipo_trans': 'Depósito',
                 'valor_trans': 3500.0},
                {'data': '2025-09-12 15:05:11',
                 'id_conta': 1,
                 'id_transacao': 2,
                 'tipo_trans': 'Saque',
                 'valor_trans': -49.4},
                {'data': '2025-09-01 11:00:00',
                 'id_conta': 2,
                 'id_transacao': 3,
                 'tipo_trans': 'Depósito',
                 'valor_trans': 25800.0},
                {'data': '2025-09-28 18:30:00',
                 'id_conta': 3,
                 'id_transacao': 4,
                 'tipo_trans': 'Depósito',
                 'valor_trans': 200000.0},
                {'data': '2025-10-02 09:12:45',
                 'id_conta': 3,
                 'id_transacao': 5,
                 'tipo_trans': 'Saque',
                 'valor_trans': -84765.02},
                {'data': '2025-08-20 16:00:01',
                 'id_conta': 4,
                 'id_transacao': 6,
                 'tipo_trans': 'Depósito',
                 'valor_trans': 189500.55},
                {'data': '2025-10-01 14:21:33',
                 'id_conta': 5,
                 'id_transacao': 7,
                 'tipo_trans': 'Depósito',
                 'valor_trans': 1000.0},
                {'data': '2025-10-03 19:55:00',
                 'id_conta': 5,
                 'id_transacao': 8,
                 'tipo_trans': 'Saque',
                 'valor_trans': -109.9},
                {'data': '2025-09-30 20:10:10',
                 'id_conta': 7,
                 'id_transacao': 9,
                 'tipo_trans': 'Saque',
                 'valor_trans': -50.25},
                {'data': '2025-10-01 00:00:00',
                 'id_conta': 2,
                 'id_transacao': 10,
                 'tipo_trans': 'Rendimento',
                 'valor_trans': 129.0},
                {'data': '2025-09-01 00:00:00',
                 'id_conta': 4,
                 'id_transacao': 11,
                 'tipo_trans': 'Rendimento',
                 'valor_trans': 947.5}]}
